use chrono::{DateTime, NaiveDate, NaiveTime, Utc};
use crate::utils::time::{
    datetime_utc_without_tz, naive_date, naive_time, opt_datetime_utc_without_tz, opt_naive_date,
    opt_naive_time,
};

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DormListData {
    pub records: Vec<DormTaskRecord>,
    pub total: i32,
    pub size: i32,
    pub current: i32,
    pub pages: i32,
}

#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct DormTaskRecord {
    #[serde(rename = "taskId")]
    pub task_id: String,
    #[serde(rename = "taskName")]
    pub task_name: String,
    #[serde(rename = "taskStartDate")]
    #[serde(with = "naive_date")]
    pub task_start_date: NaiveDate,
    #[serde(rename = "taskEndDate")]
    #[serde(with = "naive_date")]
    pub task_end_date: NaiveDate,
    #[serde(rename = "taskType")]
    pub task_type: String,
    #[serde(rename = "signStartTime")]
    #[serde(with = "naive_time")]
    pub sign_start_time: NaiveTime,
    #[serde(rename = "signEndTime")]
    #[serde(with = "naive_time")]
    pub sign_end_time: NaiveTime,
    #[serde(rename = "autoSign")]
    pub auto_sign: i32,
    #[serde(rename = "openLocate")]
    pub open_locate: i32,
    #[serde(rename = "locationAccuracy")]
    pub location_accuracy: String,
    #[serde(rename = "scanSign")]
    pub scan_sign: i32,
    #[serde(rename = "openRemind")]
    pub open_remind: i32,
    #[serde(rename = "remindTime")]
    #[serde(with = "opt_naive_time")]
    pub remind_time: Option<NaiveTime>,
    #[serde(rename = "signWeek")]
    pub sign_week: String,
    #[serde(rename = "taskStatus")]
    pub task_status: i32,
    #[serde(rename = "codeRefreshTime")]
    #[serde(with = "opt_datetime_utc_without_tz")]
    pub code_refresh_time: Option<DateTime<Utc>>,
    #[serde(rename = "openTakePhoto")]
    pub open_take_photo: Option<serde_json::Value>,
    #[serde(rename = "isFdy")]
    pub is_fdy: i32,
    #[serde(rename = "fdyTime")]
    #[serde(with = "opt_naive_time")]
    pub fdy_time: Option<NaiveTime>,
    #[serde(rename = "isUser")]
    pub is_user: i32,
    #[serde(rename = "userTime")]
    #[serde(with = "opt_naive_time")]
    pub user_time: Option<NaiveTime>,
    #[serde(rename = "isNextDay")]
    pub is_next_day: i32,
    #[serde(rename = "nextDayTime")]
    #[serde(with = "opt_naive_time")]
    pub next_day_time: Option<NaiveTime>,
    #[serde(rename = "isDormMaster")]
    pub is_dorm_master: i32,
    #[serde(rename = "dormMasterTime")]
    #[serde(with = "opt_naive_time")]
    pub dorm_master_time: Option<NaiveTime>,
    #[serde(rename = "isAllowFdyEdit")]
    pub is_allow_fdy_edit: i32,
    #[serde(rename = "isStaySchoolTask")]
    pub is_stay_school_task: i32,
    #[serde(rename = "scanType")]
    pub scan_type: String,
    #[serde(rename = "isAllowSpecialSign")]
    pub is_allow_special_sign: i32,
    #[serde(rename = "createTime")]
    #[serde(with = "datetime_utc_without_tz")]
    pub create_time: DateTime<Utc>,
    #[serde(rename = "createUser")]
    pub create_user: String,
    #[serde(rename = "updateTime")]
    #[serde(with = "opt_datetime_utc_without_tz")]
    pub update_time: Option<DateTime<Utc>>,
    #[serde(rename = "updateUser")]
    pub update_user: String,
    #[serde(rename = "isQuote")]
    pub is_quote: i32,
    #[serde(rename = "checkField")]
    pub check_field: bool,
    #[serde(rename = "userDataSql")]
    pub user_data_sql: String,
    #[serde(rename = "userDataType")]
    pub user_data_type: String,
    #[serde(rename = "taskTypeName")]
    pub task_type_name: String,
    #[serde(rename = "userId")]
    pub user_id: String,
    #[serde(rename = "leaveUserId")]
    pub leave_user_id: String,
    #[serde(rename = "signDate")]
    #[serde(with = "opt_naive_date")]
    pub sign_date: Option<NaiveDate>,
    #[serde(rename = "leaderUser")]
    pub leader_user: String,
    #[serde(rename = "notSignDates")]
    pub not_sign_dates: Vec<String>,
    #[serde(rename = "dormitoryRegisterVO")]
    pub dormitory_register_vo: serde_json::Value,
    pub leader: bool,
    #[serde(rename = "leaveFlag")]
    pub leave_flag: bool,
    #[serde(rename = "locFlag")]
    pub loc_flag: bool,
    #[serde(rename = "lxFlag")]
    pub lx_flag: bool,
    #[serde(rename = "wsFlag")]
    pub ws_flag: bool,
    #[serde(rename = "yqdCount")]
    pub yqd_count: i32,
    #[serde(rename = "qdCount")]
    pub qd_count: i32,
    #[serde(rename = "wqdCount")]
    pub wqd_count: i32,
    #[serde(rename = "leaveCount")]
    pub leave_count: i32,
    #[serde(rename = "cdCount")]
    pub cd_count: i32,
    #[serde(rename = "nowDate")]
    #[serde(with = "opt_naive_date")]
    pub now_date: Option<NaiveDate>,
    #[serde(rename = "scanTypeName")]
    pub scan_type_name: String,
    #[serde(rename = "classId")]
    pub class_id: String,
}
